services:
  vintage-story:
    image: vintage-story:local
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: vs-server
    restart: unless-stopped
    ports:
      - "42420:42420"
    volumes:
      - ./data:/srv/gameserver/data/vs
    environment:
      - TZ=Pacific/Auckland  # Set to your timezone
      - VERSION=1.22.0  # Game version - works with release candidates (unstable) as well as regular releases (stable)
    stdin_open: true
    tty: true
