services:
  vintage-story:
    image: vintage-story:local
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: vs-server
    restart: unless-stopped
    ports:
      - "42420:42420"
    volumes:
      - ./data:/srv/gameserver/data/vs
    environment:
      - TZ=Pacific/Auckland  # Set to your timezone
      - VERSION=1.22.0  # Game version - works with release candidates (unstable) as well as regular releases (stable)
      - POLAR_EQUATOR_DISTANCE=25000
      - MAP_SIZE_X=512000
      - MAP_SIZE_Z=512000
      - MODS=betterruins,watersheds,egocaribautomapmarkers,bloodtrail,walkingstick,medievalarchitecture,farseer,falandsknecht,fagothic,fahussar,deathcorpses,favarangian,fadynasties,plushiemodpack,healingsprings,offlinefoodnospoil,forestregenmod,tungsten,undergroundmines,vanillapluspatch,easybuilding,attributerenderinglibrary,ggbcsrepair,lostandfound,buzzwords,aldiclasses,stepupadvanced,charlottesclothes,xskillsgilded,vsimgui,xlibfork,xskillsfork,vsvillage,em
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/42420' 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
