services:
  vintage-story:
    image: vintage-story:local
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: vs-server
    restart: unless-stopped
    ports:
      - "42420:42420"
    volumes:
      - ./data:/srv/gameserver/data/vs
    environment:
      - TZ=Pacific/Auckland  # Set to your timezone
      - VERSION=1.22.2  # Game version - works with release candidates (unstable) as well as regular releases (stable)
      - MODS=betterruins,watersheds,egocaribautomapmarkers,bloodtrail,medievalarchitecture,falandsknecht,fagothic,fahussar,deathcorpses,favarangian,fadynasties,fajousting,faviking,fatemplar,fagreenwich,bettertraders,healingsprings,offlinefoodnospoil,forestregenmod,tungsten,undergroundmines,terraprety,easybuilding,attributerenderinglibrary,ggbcsrepair,lostandfound,buzzwords,aldiclasses,stepupadvanced,charlottesclothes,xskillsgilded,vsimgui,xlibfork,xskillsfork,em,firewoodtosticks,hardcorewaterevolved,vsextbedrespawn,antiqueharmony,antiqueensemble,realsmoke,opineuponpine,ndltreehollows,canjewelry,roomtools,butchering,automaticforging,spinningwheel,knitting,fishingplus
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/42420' 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
